apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-xeqn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tene-tenant/rhtap-demo-app/hacbs-test-project-xeqn@sha256:06b9badb03d7579555f1448c3172ba0f0f01b0a401b7c219c9a7e25905d4a9d9
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
