apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-xeqn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-xeqn
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-xeqn
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-xeqn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-xeqn
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tene-tenant/rhtap-demo-app/hacbs-test-project-xeqn@sha256:4731f4872fa26f73238d97d13658a60dda88d22fcaa3696c3393940cd57b6ebd
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
